# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10782ed280168afd15025ab74f62f1db0e28dd7d912e2ea29b1e0b935baff62c11cc0ef18f698e6833e8d82169d4b06587c87a7b9a56eae55832e864a53129fc

test:
  secret_key_base: c0d062e1f7552f979f05820c67af6bf375dfb535b65bef3135b2d20a5efe1ac90205f3938d2fc213953ea4ac7af938a301049f0ea0bd479018b761dfdb51bdda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
